version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: edugami-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: edugami
    ports:
      - "5432:5432"
    volumes:
      - edugami-pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: edugami-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - edugami-redisdata:/data

volumes:
  edugami-pgdata:
  edugami-redisdata: